###################### GENERAL ####################
###################################################
swagger:
  info:
    title: API DEMO
    description: Api de prueba basada en Spring boot
    version: 1.0.0
    contact:
      name: José Alfonso Arauco Villar - JAAV
      url: localhost:8080
      email: araucovillar@gmail.com

---
###################################################
#### PROFILE PROD ##################################
spring:
  profiles: prod
  application:
    name: myapp_demo

server:
  port: ${vcap.application.port:${PORT}}

---
###################################################
###################### PROFILE DEV ####################
###################################################
spring:
  profiles: dev
  application:
    name: myapp_demo

server:
  port: ${vcap.application.port:8088}