###################### GENERAL ####################
###################################################
swagger:
  info:
    title: API DEMO
    description: Api de prueba basada en Spring boot
    version: 1.0.0
    contact:
      name: José Alfonso Arauco Villar - JAAV
      url: localhost:8080
      email: araucovillar@gmail.com

---
###################################################
#### PROFILE PROD ##################################
spring:
  profiles: prod
  application:
    name: myapp_demo

  datasource:
    url: jdbc:h2:mem:tipocambiodb
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  # Enabling H2 Console and URL
  h2:
    console:
      enabled: true
      path: /h2

server:
  port: ${vcap.application.port:${PORT}}

---
###################################################
###################### PROFILE DEV ####################
###################################################
spring:
  profiles: dev
  application:
    name: myapp_demo

  datasource:
    url: jdbc:h2:mem:tipocambiodb
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  # Enabling H2 Console and URL
  h2:
    console:
      enabled: true
      path: /h2


server:
  port: ${vcap.application.port:8088}